"/**":
  ros__parameters:
    port: 554
    username: admin
    password: zjsxmfhf
    topic_name_prefix: /ipcam_
    transport: udp
    width: 1536
    height: 864
    publish_rate: 30.0
    use_compression: true
    jpeg_quality: 90

"ipcam_1":
  ros__parameters:
    ip: "192.168.0.27"
    camera_id: 1
    frame_id: "ipcam_1"
    K: [992.9704543278901, 0.0, 745.4080923633682, 0.0, 992.570868709759, 411.50030459149866, 0.0, 0.0, 1.0]
    new_K: [700.7187807174055, 0.0, 742.4814595173574, 0.0, 699.1715761698123, 410.1144091043476, 0.0, 0.0, 1.0]
    roi: [0, 0, 1536, 864]
    size: [1536, 864]
    dist: [-0.2748339201713551, 0.03801535894790896, 0.00011773843613683306, 0.0007567214551083291, 0.011612300134375477]
    
"ipcam_2":
  ros__parameters:
    ip: "192.168.0.21"
    camera_id: 2
    frame_id: "ipcam_2"
    K : [1039.627016222056, 0.0, 724.032103594604, 0.0, 1030.4126399697875, 379.9112839311773, 0.0, 0.0, 1.0]
    new_K : [714.0639257214872, 0.0, 714.3497270325074, 0.0, 698.82927683246, 392.23436267303174, 0.0, 0.0, 1.0]
    roi : [0, 0, 1536, 864]
    size : [1536, 864]
    dist : [-0.29279730177601715, 0.0430811875193046, 0.006354909392390921, 0.0026728851872214877, 0.008359780174727985]
    
"ipcam_3":
  ros__parameters:
    ip: "192.168.0.36"
    camera_id: 3
    frame_id: "ipcam_3"
    K: [1080.008610925944, 0.0, 779.441595151715, 0.0, 1076.4611340610697, 382.19498408518064, 0.0, 0.0, 1.0]
    new_K: [755.3707724094791, 0.0, 755.8810654059236, 0.0, 738.6560657909969, 392.05732829294317, 0.0, 0.0, 1.0]
    roi: [0, 0, 1536, 864]
    size: [1536, 864]
    dist: [-0.3181797897944729, 0.053619445884378204, 0.006513949739114805, -0.005298113217218984, 0.012064814836195823]
    
"ipcam_4":
  ros__parameters:
    ip: "192.168.0.32"
    camera_id: 4
    frame_id: "ipcam_4"
    K: [1034.685198336495, 0.0, 740.181193331419, 0.0, 1026.5168237582852, 361.18137812206544, 0.0, 0.0, 1.0]
    new_K: [699.590713941937, 0.0, 741.7249424561444, 0.0, 697.7685096320009, 368.498022424135, 0.0, 0.0, 1.0]
    roi: [0, 0, 1536, 864]
    size: [1536, 864]
    dist: [-0.3000882700638662, 0.05654237399706513, 0.006589811058608427, 0.002609065050166037, 0.002129386583769849]
    
"ipcam_5":
  ros__parameters:
    ip: "192.168.0.37"
    camera_id: 5
    frame_id: "ipcam_5"
    K: [1038.877493884038, 0.0, 764.706727340762, 0.0, 1039.0930253350282, 412.1859413259871, 0.0, 0.0, 1.0]
    new_K: [749.7599269405044, 0.0, 766.9254419970811, 0.0, 749.8131442452901, 412.3068823457312, 0.0, 0.0, 1.0]
    roi: [0, 0, 1536, 864]
    size: [1536, 864]
    dist: [-0.2839881614633001, 0.009750522722098191, 0.0005706742480525527, 0.0006186818983048614, 0.036336555761800976]

"ipcam_6":
  ros__parameters:
    ip: "192.168.0.29"
    camera_id: 6
    frame_id: "ipcam_6"
    K: [1046.83868456434, 0.0, 750.9035847155416, 0.0, 1046.6352632406392, 418.4721019491207, 0.0, 0.0, 1.0]
    new_K: [745.031221079087, 0.0, 742.5629595279396, 0.0, 741.9865648487205, 414.1984258099833, 0.0, 0.0, 1.0]
    roi:  [0, 0, 1536, 864]
    size: [1536, 864]
    dist:  [-0.3156730127862902, 0.07983236722625911, -0.0009159842294278437, -0.00015422450151715282, -0.0004889617633316215]


    