ip: 192.168.0.29
camera_id: 2
frame_id: ipcam_2
H:
- - -0.05357142857142855
  - -0.015690708150720666
  - -18.595006134993607
- - -0.05357142857142853
  - -0.07359500613499358
  - 62.16643470642216
- - -3.2526065174565133e-19
  - 0.0035714285714285696
  - 1.0
