ip: 192.168.0.20
camera_id: 14
frame_id: ipcam_14
H:
- - 0.13597870891738845
  - 0.0157776440621783
  - -125.77649254464309
- - -0.05260619503552321
  - 0.6837350441029794
  - -107.87721467021635
- - -2.168404344971009e-19
  - -0.015536914507295923
  - 1.0
