ip: 192.168.0.27
camera_id: 1
frame_id: ipcam_1
H:
- - 1.1895246692412386e-17
  - -0.07142857142857142
  - -88.57142857142854
- - -0.07576144084141576
  - -0.03571428571428567
  - 38.487322138506094
- - -2.168404344971009e-19
  - 0.0035714285714285696
  - 1.0
