ip: 192.168.0.20
camera_id: 3
frame_id: ipcam_3
H:
- - 0.05357142857142857
  - -0.015690708150720642
  - -87.16643470642218
- - -0.05357142857142857
  - -0.05140499386500637
  - -28.59500613499364
- - 2.453269466693398e-19
  - 0.0035714285714285713
  - 1.0
