ip: 192.168.0.21
port: 554
username: admin
password: zjsxmfhf
topic_name: /ip_cam/cam_2/image_raw
camera_id: 2
frame_id: camera_2_link
transport: tcp
width: 1280
height: 720
publish_rate: 60.0
H:
- - 0.13597870891738845
  - 0.0157776440621783
  - -125.77649254464309
- - -0.05260619503552321
  - 0.6837350441029794
  - -107.87721467021635
- - -2.168404344971009e-19
  - -0.015536914507295923
  - 1.0
