regions:
- id: r1
  center:
  - 43.0
  - -6.0
  points:
  - - 48.0
    - -8.0
  - - 48.0
    - -4.0
  - - 38.0
    - -4.0
  - - 38.0
    - -8.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: -0.8
- id: r2
  center:
  - 29.0
  - -6.0
  points:
  - - 36.0
    - -8.0
  - - 36.0
    - -4.0
  - - 22.0
    - -4.0
  - - 22.0
    - -8.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: -4.0
- id: r3
  center:
  - 15.0
  - -6.0
  points:
  - - 20.0
    - -8.0
  - - 20.0
    - -4.0
  - - 10.0
    - -4.0
  - - 10.0
    - -8.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: -2.0
- id: r4
  center:
  - 2.0
  - -17.0
  points:
  - - 4.0
    - -10.0
  - - 0.0
    - -10.0
  - - 4.0
    - -22.0
  - - 0.0
    - -22.0
  offset_lateral_m: 1.0
  offset_x_m: 0.8
  offset_y_m: 0.0
- id: r5
  center:
  - 0.0
  - -28.0
  points:
  - - 0.0
    - -24.0
  - - -4.0
    - -28.0
  - - -4.0
    - -32.0
  - - 0.0
    - -32.0
  - - 4.0
    - -28.0
  - - 4.0
    - -24.0
  offset_lateral_m: 1.0
  offset_x_m: 0.8
  offset_y_m: -1.2
- id: r6
  center:
  - -6.0
  - -30.0
  points:
  - - -4.0
    - -32.0
  - - -4.0
    - -28.0
  - - -8.0
    - -32.0
  - - -8.0
    - -28.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: -1.2
- id: r7
  center:
  - 16.0
  - -30.0
  points:
  - - -12.0
    - -32.0
  - - -12.0
    - -28.0
  - - -20.0
    - -32.0
  - - -20.0
    - -28.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: -1.2
- id: r8
  center:
  - -24.0
  - -34.0
  points:
  - - -20.0
    - -32.0
  - - -20.0
    - -28.0
  - - -24.0
    - -32.0
  - - -24.0
    - -42.0
  - - -28.0
    - -42.0
  - - -28.0
    - -32.0
  - - -24.0
    - -28.0
  offset_lateral_m: 1.0
  offset_x_m: 3.2
  offset_y_m: -0.4
- id: r9
  center:
  - 28.0
  - -52.0
  points:
  - - -24.0
    - -48.0
  - - -28.0
    - -48.0
  - - -30.0
    - -50.0
  - - -32.0
    - -50.0
  - - -36.0
    - -52.0
  - - -36.0
    - -56.0
  - - -28.0
    - -54.0
  offset_lateral_m: 1.0
  offset_x_m: 0.4
  offset_y_m: -2.0
- id: r10
  center:
  - 42.0
  - -52.0
  points:
  - - -36.0
    - -48.0
  - - -36.0
    - -56.0
  - - -52.0
    - -48.0
  - - -52.0
    - -56.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: -0.8
- id: r11
  center:
  - -48.0
  - -56.0
  points:
  - - -52.0
    - -52.0
  - - -52.0
    - -56.0
  - - -56.0
    - -54.0
  - - -60.0
    - -48.0
  - - -60.0
    - -40.0
  - - -56.0
    - -40.0
  - - -56.0
    - -48.0
  offset_lateral_m: 1.0
  offset_x_m: -0.8
  offset_y_m: -0.8
- id: r12
  center:
  - 42.0
  - -52.0
  points:
  - - -60.0
    - -40.0
  - - -56.0
    - -40.0
  - - -60.0
    - -16.0
  - - -56.0
    - -16.0
  offset_lateral_m: 1.0
  offset_x_m: -0.8
  offset_y_m: 0.0
- id: r13
  center:
  - 42.0
  - -52.0
  points:
  - - -60.0
    - -16.0
  - - -60.0
    - 0.0
  - - -44.0
    - 0.0
  - - -44.0
    - -4.0
  - - -52.0
    - -4.0
  - - -56.0
    - -8.0
  - - -56.0
    - -16.0
  offset_lateral_m: 1.0
  offset_x_m: -0.4
  offset_y_m: 1.2
- id: r14
  center:
  - 2.0
  - -17.0
  points:
  - - 4.0
    - -22.0
  - - 0.0
    - -22.0
  - - 4.0
    - -24.0
  - - 0.0
    - -24.0
  - - 4.0
    - -28.0
  - - 12.0
    - -28.0
  - - 12.0
    - -24.0
  offset_lateral_m: 1.0
  offset_x_m: -0.8
  offset_y_m: 2.0
- id: r15
  center:
  - 2.0
  - -17.0
  points:
  - - 20.0
    - -24.0
  - - 20.0
    - -28.0
  - - 32.0
    - -24.0
  - - 32.0
    - -36.0
  - - 28.0
    - -36.0
  - - 28.0
    - -32.0
  - - 24.0
    - -28.0
  offset_lateral_m: 1.0
  offset_x_m: 1.2
  offset_y_m: -0.8
- id: r16
  center:
  - 2.0
  - -17.0
  points:
  - - 28.0
    - -36.0
  - - 32.0
    - -36.0
  - - 28.0
    - -44.0
  - - 32.0
    - -44.0
  offset_lateral_m: 1.0
  offset_x_m: 1.2
  offset_y_m: -0.8
- id: r17
  center:
  - 2.0
  - -17.0
  points:
  - - 28.0
    - -44.0
  - - 32.0
    - -44.0
  - - 28.0
    - -48.0
  - - 36.0
    - -48.0
  - - 44.0
    - -48.0
  - - 44.0
    - -52.0
  - - 28.0
    - -44.0
  - - 32.0
    - -50.0
  - - 30.0
    - -48.0
  offset_lateral_m: 1.0
  offset_x_m: -0.8
  offset_y_m: 2.4
- id: r18
  center:
  - 2.0
  - -17.0
  points:
  - - 48.0
    - -48.0
  - - 48.0
    - -52.0
  - - 52.0
    - -50.0
  - - 56.0
    - -48.0
  - - 56.0
    - -40.0
  - - 52.0
    - -40.0
  - - 52.0
    - -46.0
  offset_lateral_m: 1.0
  offset_x_m: -2.0
  offset_y_m: 0.4
- id: r18
  center:
  - 2.0
  - -17.0
  points:
  - - 52.0
    - -40.0
  - - 52.0
    - -20.0
  - - 56.0
    - -40.0
  - - 56.0
    - -20.0
  offset_lateral_m: 1.0
  offset_x_m: -0.4
  offset_y_m: 0.0
- id: r19
  center:
  - 2.0
  - -17.0
  points:
  - - 56.0
    - -40.0
  - - 56.0
    - -20.0
  - - 60.0
    - -40.0
  - - 60.0
    - -20.0
  offset_lateral_m: 1.0
  offset_x_m: 0.4
  offset_y_m: 0.0
description: Regions for geometric offset along global paths. offset_lateral_m is
  applied along lane normal; offset_x_m, offset_y_m are world X/Y shifts.