regions:
- id: r1
  center:
  - 30.449999999999996
  - -3.7544730435247007
  points:
  - - 18.91304347826086
    - 0.28030956517095174
  - - 41.98695652173913
    - 0.28030956517095174
  - - 41.98695652173913
    - -7.789255652220353
  - - 18.91304347826086
    - -7.789255652220353
  offset_lateral_m: 0.0
  offset_x_m: 0.0
  offset_y_m: -3.0
description: Regions for geometric offset along global paths. offset_lateral_m is
  applied along lane normal; offset_x_m, offset_y_m are world X/Y shifts.
