regions:
- id: r1
  center:
  - 43.0
  - -6.0
  points:
  - - -60.0
    - -40.0
  - - -52.0
    - -40.0
  - - -50.8
    - -42.8
  - - -48.0
    - -44.0
  - - -48.0
    - -52.0
  - - -52.0
    - -52.0
  - - -57.6
    - -49.6
  - - -60.0
    - -44.0    
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r2
  center:
  - 29.0
  - -6.0
  points:
  - - -48.0
    - -52.0
  - - -48.0
    - -44.0
  - - -44.8
    - -52.8
  - - -44.0
    - -44.0
  - - -40.0
    - -52.0
  - - -40.0
    - -44.0
  - - -36.0
    - -52.0
  - - -36.0
    - -44.0 
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r3
  center:
  - 15.0
  - -6.0
  points:
  - - -36.0
    - -52.0
  - - -36.0
    - -44.0
  - - -33.2
    - -42.8
  - - -32.0
    - -40.0
  - - -24.0
    - -40.0
  - - -24.0
    - -44.0
  - - -26.4
    - -49.6
  - - -32.0
    - -52.0 
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r4
  center:
  - 2.0
  - -17.0
  points:
  - - -24.0
    - -40.0
  - - -32.0
    - -40.0
  - - -24.8
    - -36.8
  - - -32.0
    - -36.0
  - - -24.0
    - -32.0
  - - -32.0
    - -32.0 
  offset_lateral_m: 1.0
  offset_x_m: 0.8
  offset_y_m: 0.0
- id: r5
  center:
  - 0.0
  - -28.0
  points:
  - - -24.0
    - -32.0
  - - -32.0
    - -32.0
  - - -32.0
    - -28.0
  - - -29.6
    - -22.4
  - - -24.0
    - -20.0
  - - -20.0
    - -20.0
  - - -20.0
    - -28.0
  - - -22.8
    - -29.2 
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r6
  center:
  - -6.0
  - -30.0
  points:
  - - -20.0
    - -28.0
  - - -20.0
    - -20.0
  - - -16.0
    - -28.0
  - - -16.0
    - -20.0
  - - -12.0
    - -28.0
  - - -12.0
    - -20.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 3.0
- id: r7
  center:
  - 16.0
  - -30.0
  points:
  - - -12.0
    - -28.0
  - - -12.0
    - -20.0
  - - -8.0
    - -28.0
  - - -8.0
    - -20.0
  - - -4.0
    - -28.0
  - - -4.0
    - -20.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 4.0
- id: r8
  center:
  - -24.0
  - -34.0
  points:
  - - 4.0
    - -28.0
  - - 4.0
    - -20.0
  - - 8.0
    - -28.0
  - - 8.0
    - -20.0
  - - 12.0
    - -28.0
  - - 12.0
    - -20.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r9
  center:
  - 28.0
  - -52.0
  points:
  - - 12.0
    - -28.0
  - - 12.0
    - -20.0
  - - 16.0
    - -28.0
  - - 16.0
    - -20.0
  - - 20.0
    - -28.0
  - - 20.0
    - -20.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r10
  center:
  - 42.0
  - -52.0
  points:
  - - 20.0
    - -28.0
  - - 20.0
    - -20.0
  - - 24.0
    - -20.0
  - - 29.6
    - -22.4
  - - 32.0
    - -28.0
  - - 32.0
    - -32.0
  - - 24.0
    - -32.0  
  - - 22.8
    - -29.2
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: -0.0
- id: r11
  center:
  - -48.0
  - -56.0
  points:
  - - 24.0
    - -32.0
  - - 32.0
    - -32.0
  - - 24.0
    - -36.0
  - - 32.0
    - -36.0
  - - 24.0
    - -40.0
  - - 32.0
    - -40.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r12
  center:
  - 42.0
  - -52.0
  points:
  - - 24.0
    - -40.0
  - - 32.0
    - -40.0
  - - 34.8
    - -42.8
  - - 36.0
    - -44.0
  - - 36.0
    - -52.0
  - - 32.0
    - -52.0
  - - 26.4
    - -49.6
  offset_lateral_m: 1.0
  offset_x_m: -0.0
  offset_y_m: 0.0
- id: r13
  center:
  - 42.0
  - -52.0
  points:
  - - 36.0
    - -52.0
  - - 36.0
    - -44.0
  - - 40.0
    - -52.0
  - - 40.0
    - -44.0
  - - 44.0
    - -52.0
  - - 44.0
    - -44.0
  - - 48.0
    - -52.0
  - - 48.0
    - -44.0
  offset_lateral_m: 1.0
  offset_x_m: -0.0
  offset_y_m: 0.0
- id: r14
  center:
  - 2.0
  - -17.0
  points:
  - - 48.0
    - -52.0
  - - 48.0
    - -44.0
  - - 50.8
    - -42.8
  - - 52.0
    - -40.0
  - - 60.0
    - -40.0
  - - 60.0
    - -44.0
  - - 57.6
    - -49.6
  - - 52.0
    - -52.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r15
  center:
  - 2.0
  - -17.0
  points:
  - - 60.0
    - -40.0
  - - 52.0
    - -40.0
  - - 60.0
    - -36.0
  - - 52.0
    - -36.0
  - - 60.0
    - -32.0
  - - 52.0
    - -32.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r16
  center:
  - 2.0
  - -17.0
  points:
  - - 60.0
    - -32.0
  - - 52.0
    - -32.0
  - - 60.0
    - -28.0
  - - 52.0
    - -28.0
  - - 60.0
    - -24.0
  - - 52.0
    - -24.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r17
  center:
  - 2.0
  - -17.0
  points:
  - - 60.0
    - -24.0
  - - 52.0
    - -24.0
  - - 60.0
    - -20.0
  - - 52.0
    - -20.0
  - - 60.0
    - -16.0
  - - 52.0
    - -16.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r18
  center:
  - 2.0
  - -17.0
  points:
  - - 60.0
    - -16.0
  - - 52.0
    - -16.0
  - - 60.0
    - -12.0
  - - 52.0
    - -12.0
  - - 60.0
    - -8.0
  - - 52.0
    - -8.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r19
  center:
  - 2.0
  - -17.0
  points:
  - - 60.0
    - -8.0
  - - 52.0
    - -8.0
  - - 50.8
    - -5.2
  - - 48.0
    - -4.0
  - - 48.0
    - 4.0
  - - 52.0
    - 4.0
  - - 57.6
    - 2.4
  - - 60.0
    - -4.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r20
  center:
  - 2.0
  - -17.0
  points:
  - - 48.0
    - 4.0
  - - 48.0
    - -4.0
  - - 44.0
    - 4.0
  - - 44.0
    - -4.0
  - - 40.0
    - 4.0
  - - 40.0
    - -4.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r21
  center:
  - 2.0
  - -17.0
  points:
  - - 40.0
    - 4.0
  - - 40.0
    - -4.0
  - - 36.0
    - 4.0
  - - 36.0
    - -4.0
  - - 32.0
    - 4.0
  - - 32.0
    - -4.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r22
  center:
  - 2.0
  - -17.0
  points:
  - - 32.0
    - 4.0
  - - 32.0
    - -4.0
  - - 28.0
    - 4.0
  - - 28.0
    - -4.0
  - - 24.0
    - 4.0
  - - 24.0
    - -4.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r23
  center:
  - 2.0
  - -17.0
  points:
  - - 24.0
    - 4.0
  - - 24.0
    - -4.0
  - - 20.0
    - 4.0
  - - 20.0
    - -4.0
  - - 16.0
    - 4.0
  - - 16.0
    - -4.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r24
  center:
  - 2.0
  - -17.0
  points:
  - - -16.0
    - 4.0
  - - -16.0
    - -4.0
  - - -20.0
    - 4.0
  - - -20.0
    - -4.0
  - - -24.0
    - 4.0
  - - -24.0
    - -4.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r25
  center:
  - 2.0
  - -17.0
  points:
  - - -24.0
    - 4.0
  - - -24.0
    - -4.0
  - - -28.0
    - 4.0
  - - -28.0
    - -4.0
  - - -32.0
    - 4.0
  - - -32.0
    - -4.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r26
  center:
  - 2.0
  - -17.0
  points:
  - - -32.0
    - 4.0
  - - -32.0
    - -4.0
  - - -36.0
    - 4.0
  - - -36.0
    - -4.0
  - - -40.0
    - 4.0
  - - -40.0
    - -4.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r27
  center:
  - 2.0
  - -17.0
  points:
  - - -40.0
    - 4.0
  - - -40.0
    - -4.0
  - - -44.0
    - 4.0
  - - -44.0
    - -4.0
  - - -48.0
    - 4.0
  - - -48.0
    - -4.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r28
  center:
  - 2.0
  - -17.0
  points:
  - - -48.0
    - 4.0
  - - -52.0
    - 4.0
  - - -57.6
    - 2.4
  - - -60.0
    - -4.0
  - - -60.0
    - -8.0
  - - -52.0
    - -8.0
  - - -50.8
    - -5.2
  - - -48.0
    - -4.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r29
  center:
  - 2.0
  - -17.0
  points:
  - - -60.0
    - -8.0
  - - -52.0
    - -8.0
  - - -60.0
    - -12.0
  - - -52.0
    - -12.0
  - - -60.0
    - -16.0
  - - -52.0
    - -16.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r30
  center:
  - 2.0
  - -17.0
  points:
  - - -60.0
    - -16.0
  - - -52.0
    - -16.0
  - - -60.0
    - -20.0
  - - -52.0
    - -20.0
  - - -60.0
    - -24.0
  - - -52.0
    - -24.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r31
  center:
  - 2.0
  - -17.0
  points:
  - - -60.0
    - -24.0
  - - -52.0
    - -24.0
  - - -60.0
    - -28.0
  - - -52.0
    - -28.0
  - - -60.0
    - -32.0
  - - -52.0
    - -32.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r32
  center:
  - 2.0
  - -17.0
  points:
  - - -60.0
    - -32.0
  - - -52.0
    - -32.0
  - - -60.0
    - -36.0
  - - -52.0
    - -36.0
  - - -60.0
    - -40.0
  - - -52.0
    - -40.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r33
  center:
  - 2.0
  - -17.0
  points:
  - - 12.0
    - 0.0
  - - 9.8
    - -9.8
  - - 0.0
    - -12.0
  - - 0.0
    - 0.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r34
  center:
  - 2.0
  - -17.0
  points:
  - - 0.0
    - -12.0
  - - -9.8
    - -9.8
  - - -12.0
    - 0.0
  - - 0.0
    - 0.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r35
  center:
  - 2.0
  - -17.0
  points:
  - - 12.0
    - 0.0
  - - -9.8
    - 9.8
  - - 0.0
    - 12.0
  - - 0.0
    - 0.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r36
  center:
  - 2.0
  - -17.0
  points:
  - - 0.0
    - 12.0
  - - 9.8
    - 9.8
  - - 12.0
    - 0.0
  - - 0.0
    - 0.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r37
  center:
  - 2.0
  - -17.0
  points:
  - - 0.0
    - -8.0
  - - -4.0
    - -8.0
  - - 0.0
    - -12.0
  - - -4.0
    - -12.0
  - - 0.0
    - -16.0
  - - -4.0
    - -16.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r38
  center:
  - 2.0
  - -17.0
  points:
  - - 0.0
    - -8.0
  - - 4.0
    - -8.0
  - - 0.0
    - -12.0
  - - 4.0
    - -12.0
  - - 0.0
    - -16.0
  - - 4.0
    - -16.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r39
  center:
  - 2.0
  - -17.0
  points:
  - - -4.0
    - -16.0
  - - 0.0
    - -16.0
  - - 0.0
    - -20.0
  - - 4.0
    - -24.0
  - - 4.0
    - -28.0
  - - 0.0
    - -24.0
  - - -4.0
    - -20.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
- id: r40
  center:
  - 2.0
  - -17.0
  points:
  - - 4.0
    - -16.0
  - - 0.0
    - -16.0
  - - 0.0
    - -20.0
  - - -4.0
    - -24.0
  - - -4.0
    - -28.0
  - - 0.0
    - -24.0
  - - 4.0
    - -20.0
  offset_lateral_m: 1.0
  offset_x_m: 0.0
  offset_y_m: 0.0
description: Regions for geometric offset along global paths. offset_lateral_m is
  applied along lane normal; offset_x_m, offset_y_m are world X/Y shifts.